### PR TITLE
feat: added landing page

### PR DESCRIPTION
**Pull request by shahbazibnafzal**
Added landing page

### CODE REVIEW

**Comment by scjuly19** [comment]
Looks awesome, great work on the UI and responsiveness

**Review by scjuly19 — APPROVED** [review]

**Review by Hamza-777 — APPROVED** [review]
Looks really awesome just the image of indian players looks a little off because of maybe less height to it it looks flattened a bit.

**Comment by hsnice16** [comment]
UI is awesome, great work on that. Just one suggestion, don't you think the distance between brand-name and brand-logo is a bit large.
image

**Review by hsnice16 — APPROVED** [review]

**Comment by shahbazibnafzal** [comment]
Thanks for the review and great feedbacks @scjuly19 , @Hamza-777  and @hsnice16. I have incorporated all the feedbacks received, merging it to dev

**Pull request merged**
